### ISSUE TITLE
Support latest release of Twemproxy

### ISSUE THREAD

**Issue by aljinovic** [malexer/docker-twemproxy#2]
Hello, there's a new release of Twemproxy available: https://github.com/twitter/twemproxy/releases

Would you be interested in upgrading the docker image?

**Comment by malexer** [comment]
I have prepared a new docker image with the following upgrades:
- twemproxy to 0.5.0
- Alpine base image to 3.14

You can find the new image on a Docker Hub.

@aljinovic Please, let me know if it works as expected.

**Comment by aljinovic** [comment]
Thanks, works as expected!

**Comment by malexer** [comment]
Great, thanks for the feedback.
Closing the issue
